const FLAG_OVERRIDES: Record<string, string> = {
  EUR: '🇪🇺',
  XAF: '🌍',
  XOF: '🌍',
  XPF: '🌏',
  XCD: '🌎',
  XDR: '🏦',
  ANG: '🇨🇼',
};

export const CURRENCY_NAMES: Record<string, string> = {
  AED: 'Дирхам ОАЭ',
  AFN: 'Афгани',
  ALL: 'Албанский лек',
  AMD: 'Армянский драм',
  ANG: 'Нидерландский антильский гульден',
  AOA: 'Ангольская кванза',
  ARS: 'Аргентинское песо',
  AUD: 'Австралийский доллар',
  AWG: 'Арубанский флорин',
  AZN: 'Азербайджанский манат',
  BAM: 'Боснийская марка',
  BBD: 'Барбадосский доллар',
  BDT: 'Бангладешская така',
  BGN: 'Болгарский лев',
  BHD: 'Бахрейнский динар',
  BIF: 'Бурундийский франк',
  BMD: 'Бермудский доллар',
  BND: 'Брунейский доллар',
  BOB: 'Боливиано',
  BRL: 'Бразильский реал',
  BSD: 'Багамский доллар',
  BTN: 'Бутанский нгултрум',
  BWP: 'Ботсванская пула',
  BYN: 'Белорусский рубль',
  BZD: 'Белизский доллар',
  CAD: 'Канадский доллар',
  CDF: 'Конголезский франк',
  CHF: 'Швейцарский франк',
  CLP: 'Чилийское песо',
  CNY: 'Китайский юань',
  COP: 'Колумбийское песо',
  CRC: 'Костариканский колон',
  CUP: 'Кубинское песо',
  CVE: 'Эскудо Кабо-Верде',
  CZK: 'Чешская крона',
  DJF: 'Франк Джибути',
  DKK: 'Датская крона',
  DOP: 'Доминиканское песо',
  DZD: 'Алжирский динар',
  EGP: 'Египетский фунт',
  ERN: 'Эритрейская накфа',
  ETB: 'Эфиопский быр',
  EUR: 'Евро',
  FJD: 'Фиджийский доллар',
  FKP: 'Фунт Фолклендских островов',
  FOK: 'Фарерская крона',
  GBP: 'Фунт стерлингов',
  GEL: 'Грузинский лари',
  GGP: 'Гернсийский фунт',
  GHS: 'Ганский седи',
  GIP: 'Гибралтарский фунт',
  GMD: 'Гамбийский даласи',
  GNF: 'Гвинейский франк',
  GTQ: 'Гватемальский кетсаль',
  GYD: 'Гайанский доллар',
  HKD: 'Гонконгский доллар',
  HNL: 'Гондурасская лемпира',
  HRK: 'Хорватская куна',
  HTG: 'Гаитянский гурд',
  HUF: 'Венгерский форинт',
  IDR: 'Индонезийская рупия',
  ILS: 'Израильский шекель',
  IMP: 'Мэнский фунт',
  INR: 'Индийская рупия',
  IQD: 'Иракский динар',
  IRR: 'Иранский риал',
  ISK: 'Исландская крона',
  JEP: 'Джерсийский фунт',
  JMD: 'Ямайский доллар',
  JOD: 'Иорданский динар',
  JPY: 'Японская иена',
  KES: 'Кенийский шиллинг',
  KGS: 'Киргизский сом',
  KHR: 'Камбоджийский риель',
  KID: 'Доллар Кирибати',
  KMF: 'Коморский франк',
  KRW: 'Южнокорейская вона',
  KWD: 'Кувейтский динар',
  KYD: 'Доллар Каймановых островов',
  KZT: 'Казахстанский тенге',
  LAK: 'Лаосский кип',
  LBP: 'Ливанский фунт',
  LKR: 'Шри-Ланкийская рупия',
  LRD: 'Либерийский доллар',
  LSL: 'Лесотский лоти',
  LYD: 'Ливийский динар',
  MAD: 'Марокканский дирхам',
  MDL: 'Молдавский лей',
  MGA: 'Малагасийский ариари',
  MKD: 'Македонский денар',
  MMK: 'Мьянманский кьят',
  MNT: 'Монгольский тугрик',
  MOP: 'Патака Макао',
  MRU: 'Мавританская угия',
  MUR: 'Маврикийская рупия',
  MVR: 'Мальдивская руфия',
  MWK: 'Малавийская квача',
  MXN: 'Мексиканское песо',
  MYR: 'Малайзийский ринггит',
  MZN: 'Мозамбикский метикал',
  NAD: 'Намибийский доллар',
  NGN: 'Нигерийская найра',
  NIO: 'Никарагуанская кордоба',
  NOK: 'Норвежская крона',
  NPR: 'Непальская рупия',
  NZD: 'Новозеландский доллар',
  OMR: 'Оманский риал',
  PAB: 'Панамский бальбоа',
  PEN: 'Перуанский соль',
  PGK: 'Кина Папуа-Новой Гвинеи',
  PHP: 'Филиппинское песо',
  PKR: 'Пакистанская рупия',
  PLN: 'Польский злотый',
  PYG: 'Парагвайский гуарани',
  QAR: 'Катарский риал',
  RON: 'Румынский лей',
  RSD: 'Сербский динар',
  RUB: 'Российский рубль',
  RWF: 'Руандийский франк',
  SAR: 'Саудовский риял',
  SBD: 'Доллар Соломоновых островов',
  SCR: 'Сейшельская рупия',
  SDG: 'Суданский фунт',
  SEK: 'Шведская крона',
  SGD: 'Сингапурский доллар',
  SHP: 'Фунт Святой Елены',
  SLE: 'Сьерра-Леонский леоне',
  SLL: 'Сьерра-Леонский леоне',
  SOS: 'Сомалийский шиллинг',
  SRD: 'Суринамский доллар',
  SSP: 'Южносуданский фунт',
  STN: 'Добра Сан-Томе и Принсипи',
  SYP: 'Сирийский фунт',
  SZL: 'Свазилендский лилангени',
  THB: 'Тайский бат',
  TJS: 'Таджикский сомони',
  TMT: 'Туркменский манат',
  TND: 'Тунисский динар',
  TOP: 'Тонганская паанга',
  TRY: 'Турецкая лира',
  TTD: 'Доллар Тринидада и Тобаго',
  TVD: 'Доллар Тувалу',
  TWD: 'Тайваньский доллар',
  TZS: 'Танзанийский шиллинг',
  UAH: 'Украинская гривна',
  UGX: 'Угандийский шиллинг',
  USD: 'Доллар США',
  UYU: 'Уругвайское песо',
  UZS: 'Узбекский сум',
  VES: 'Венесуэльский боливар',
  VND: 'Вьетнамский донг',
  VUV: 'Вануатский вату',
  WST: 'Самоанская тала',
  XAF: 'Франк КФА BEAC',
  XCD: 'Восточнокарибский доллар',
  XDR: 'Специальные права заимствования',
  XOF: 'Франк КФА BCEAO',
  XPF: 'Франк КФП',
  YER: 'Йеменский риал',
  ZAR: 'Южноафриканский рэнд',
  ZMW: 'Замбийская квача',
  ZWL: 'Зимбабвийский доллар',
};

export function getFlagForCurrency(code: string): string {
  if (FLAG_OVERRIDES[code]) return FLAG_OVERRIDES[code];
  if (code.length < 2) return '💱';
  const c1 = code.codePointAt(0)!;
  const c2 = code.codePointAt(1)!;
  return String.fromCodePoint(c1 - 0x41 + 0x1F1E6, c2 - 0x41 + 0x1F1E6);
}

const CURRENCY_KEYWORDS: Record<string, string> = {
  AED: 'ОАЭ Эмираты UAE United Arab Emirates',
  AFN: 'Афганистан Afghanistan',
  ALL: 'Албания Albania',
  AMD: 'Армения Armenia',
  ANG: 'Нидерланды Антилы Netherlands Antilles Curacao Кюрасао',
  AOA: 'Ангола Angola',
  ARS: 'Аргентина Argentina',
  AUD: 'Австралия Australia',
  AWG: 'Аруба Aruba',
  AZN: 'Азербайджан Azerbaijan',
  BAM: 'Босния Герцеговина Bosnia Herzegovina',
  BBD: 'Барбадос Barbados',
  BDT: 'Бангладеш Bangladesh',
  BGN: 'Болгария Bulgaria',
  BHD: 'Бахрейн Bahrain',
  BIF: 'Бурунди Burundi',
  BMD: 'Бермуды Bermuda',
  BND: 'Бруней Brunei',
  BOB: 'Боливия Bolivia',
  BRL: 'Бразилия Brazil',
  BSD: 'Багамы Bahamas',
  BTN: 'Бутан Bhutan',
  BWP: 'Ботсвана Botswana',
  BYN: 'Беларусь Белоруссия Belarus',
  BZD: 'Белиз Belize',
  CAD: 'Канада Canada',
  CDF: 'Конго Congo',
  CHF: 'Швейцария Switzerland',
  CLP: 'Чили Chile',
  CNY: 'Китай China',
  COP: 'Колумбия Colombia',
  CRC: 'Коста-Рика Costa Rica',
  CUP: 'Куба Cuba',
  CVE: 'Кабо-Верде Cape Verde',
  CZK: 'Чехия Czech Czechia',
  DJF: 'Джибути Djibouti',
  DKK: 'Дания Denmark',
  DOP: 'Доминикана Dominican Republic',
  DZD: 'Алжир Algeria',
  EGP: 'Египет Egypt',
  ERN: 'Эритрея Eritrea',
  ETB: 'Эфиопия Ethiopia',
  EUR: 'Европа Евросоюз Europe European Union',
  FJD: 'Фиджи Fiji',
  FKP: 'Фолкленды Falkland Islands',
  FOK: 'Фареры Faroe Islands',
  GBP: 'Великобритания Англия United Kingdom Britain England',
  GEL: 'Грузия Georgia',
  GGP: 'Гернси Guernsey',
  GHS: 'Гана Ghana',
  GIP: 'Гибралтар Gibraltar',
  GMD: 'Гамбия Gambia',
  GNF: 'Гвинея Guinea',
  GTQ: 'Гватемала Guatemala',
  GYD: 'Гайана Guyana',
  HKD: 'Гонконг Hong Kong',
  HNL: 'Гондурас Honduras',
  HRK: 'Хорватия Croatia',
  HTG: 'Гаити Haiti',
  HUF: 'Венгрия Hungary',
  IDR: 'Индонезия Indonesia',
  ILS: 'Израиль Israel',
  IMP: 'Остров Мэн Isle of Man',
  INR: 'Индия India',
  IQD: 'Ирак Iraq',
  IRR: 'Иран Iran',
  ISK: 'Исландия Iceland',
  JEP: 'Джерси Jersey',
  JMD: 'Ямайка Jamaica',
  JOD: 'Иордания Jordan',
  JPY: 'Япония Japan',
  KES: 'Кения Kenya',
  KGS: 'Киргизия Кыргызстан Kyrgyzstan',
  KHR: 'Камбоджа Cambodia',
  KID: 'Кирибати Kiribati',
  KMF: 'Коморы Comoros',
  KRW: 'Южная Корея South Korea',
  KWD: 'Кувейт Kuwait',
  KYD: 'Каймановы острова Cayman Islands',
  KZT: 'Казахстан Kazakhstan',
  LAK: 'Лаос Laos',
  LBP: 'Ливан Lebanon',
  LKR: 'Шри-Ланка Sri Lanka',
  LRD: 'Либерия Liberia',
  LSL: 'Лесото Lesotho',
  LYD: 'Ливия Libya',
  MAD: 'Марокко Morocco',
  MDL: 'Молдова Молдавия Moldova',
  MGA: 'Мадагаскар Madagascar',
  MKD: 'Македония Macedonia North Macedonia',
  MMK: 'Мьянма Бирма Myanmar Burma',
  MNT: 'Монголия Mongolia',
  MOP: 'Макао Macao Macau',
  MRU: 'Мавритания Mauritania',
  MUR: 'Маврикий Mauritius',
  MVR: 'Мальдивы Maldives',
  MWK: 'Малави Malawi',
  MXN: 'Мексика Mexico',
  MYR: 'Малайзия Malaysia',
  MZN: 'Мозамбик Mozambique',
  NAD: 'Намибия Namibia',
  NGN: 'Нигерия Nigeria',
  NIO: 'Никарагуа Nicaragua',
  NOK: 'Норвегия Norway',
  NPR: 'Непал Nepal',
  NZD: 'Новая Зеландия New Zealand',
  OMR: 'Оман Oman',
  PAB: 'Панама Panama',
  PEN: 'Перу Peru',
  PGK: 'Папуа-Новая Гвинея Papua New Guinea',
  PHP: 'Филиппины Philippines',
  PKR: 'Пакистан Pakistan',
  PLN: 'Польша Poland',
  PYG: 'Парагвай Paraguay',
  QAR: 'Катар Qatar',
  RON: 'Румыния Romania',
  RSD: 'Сербия Serbia',
  RUB: 'Россия Russia',
  RWF: 'Руанда Rwanda',
  SAR: 'Саудовская Аравия Saudi Arabia',
  SBD: 'Соломоновы острова Solomon Islands',
  SCR: 'Сейшелы Seychelles',
  SDG: 'Судан Sudan',
  SEK: 'Швеция Sweden',
  SGD: 'Сингапур Singapore',
  SHP: 'Святая Елена Saint Helena',
  SLE: 'Сьерра-Леоне Sierra Leone',
  SLL: 'Сьерра-Леоне Sierra Leone',
  SOS: 'Сомали Somalia',
  SRD: 'Суринам Suriname',
  SSP: 'Южный Судан South Sudan',
  STN: 'Сан-Томе Принсипи Sao Tome Principe',
  SYP: 'Сирия Syria',
  SZL: 'Эсватини Свазиленд Eswatini Swaziland',
  THB: 'Таиланд Thailand',
  TJS: 'Таджикистан Tajikistan',
  TMT: 'Туркменистан Turkmenistan',
  TND: 'Тунис Tunisia',
  TOP: 'Тонга Tonga',
  TRY: 'Турция Turkey Türkiye',
  TTD: 'Тринидад Тобаго Trinidad Tobago',
  TVD: 'Тувалу Tuvalu',
  TWD: 'Тайвань Taiwan',
  TZS: 'Танзания Tanzania',
  UAH: 'Украина Ukraine',
  UGX: 'Уганда Uganda',
  USD: 'США Америка USA America United States',
  UYU: 'Уругвай Uruguay',
  UZS: 'Узбекистан Uzbekistan',
  VES: 'Венесуэла Venezuela',
  VND: 'Вьетнам Vietnam',
  VUV: 'Вануату Vanuatu',
  WST: 'Самоа Samoa',
  XAF: 'Центральная Африка Central Africa',
  XCD: 'Восточные Карибы Eastern Caribbean',
  XDR: 'МВФ IMF',
  XOF: 'Западная Африка West Africa',
  XPF: 'Французская Полинезия French Polynesia',
  YER: 'Йемен Yemen',
  ZAR: 'ЮАР Южная Африка South Africa',
  ZMW: 'Замбия Zambia',
  ZWL: 'Зимбабве Zimbabwe',
};

export function getCurrencyName(code: string): string {
  return CURRENCY_NAMES[code] || code;
}

export function getCurrencyKeywords(code: string): string {
  return CURRENCY_KEYWORDS[code] || '';
}

export interface CurrencyItem {
  code: string;
  flag: string;
  name: string;
  keywords: string;
}

export function buildCurrencyList(codes: string[]): CurrencyItem[] {
  return codes
    .slice()
    .sort((a, b) => a.localeCompare(b))
    .map(code => ({
      code,
      flag: getFlagForCurrency(code),
      name: getCurrencyName(code),
      keywords: getCurrencyKeywords(code).toLowerCase(),
    }));
}
